spring.application.name=authy
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.config.import=optional:configserver:http://localhost:8888

server.port=8081

JWT_SECRET_KEY=${JWT_SECRET_KEY:your_default_secret_here}
#expiration is set to one minute.
JWT_EXPIRATION=60000
#expiration is set to seven days.
REFRESH_EXPIRATION=604800000

spring.web.resources.static-locations=file:uploads/

#spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
#spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
#spring.security.oauth2.client.registration.google.scope=profile,email

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/authy}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:omar}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_password_here}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
